### PR TITLE
%+O inspects with colors

### PR DESCRIPTION
**Pull request by qlba**

### CODE REVIEW

**Comment by wdavidw** [comment]
Could you point me to the official documentation of the functionnality ? I'll need to update the doc

**Comment by qlba** [comment]
You mean I need to add description of added functionality in docs?

**Comment by wdavidw** [comment]
I was more asking for an official specification which covers the functionality to link the doc.

**Comment by qlba** [comment]
https://nodejs.org/dist/latest-v8.x/docs/api/util.html#util_util_inspect_object_options
options > colors

**Comment by wdavidw** [comment]
Sorry, I meant the printf specification

**Comment by wdavidw** [comment]
This is probably no standard functionnality, I just want to make sure where you got the "+" sign from.

**Comment by wdavidw** [comment]
Thank you for the contribution

**Comment by qlba** [comment]
I'm glad to be helpful

**Pull request merged**
